language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  #- "nightly"
  - "pypy"
#install: "pip install -r requirements.txt"
script:
  - python -m compileall -f .
  - python setup.py test
  #- python -m unittest discover -v
